<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container">

            <div class="row">
                <div class="col-xs-12">
                    <div class="page-title-box">
                        <h4 class="page-title">Configuracion</h4>
                        <ol class="breadcrumb p-0">
                            <li>
                                <a href="#">Tablas</a>
                            </li>
                            <li class="active">
                                <?= ucwords("$model"); ?>
                            </li>
                        </ol>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <!-- end row -->

            <div class="row">
                <div class="col-sm-12">

                    <div id="scaffold" class="card-box table-responsive">
                    <?php View::content()?>
                        <div class="page-header">
                            <div class="row">
                                <div class="col-xs-6">
                                    
                                    
                                </div>
                                <div class="col-xs-6">
                                    <?php echo Html::img('logoatlantico.png',null,'width="80%" height="80%"')?>
                                </div>
                                
                            </div>
                            <div class="row">
                                <h1><?= "<span>Reporte </span>", ucwords("$model")  ?></h1>
                            </div>
<!--                            <div class="actions">
                                <?= Html::linkAction("crear/", 'Crear registro', 'class="btn btn-primary"')?>
                            </div>-->
                        </div>
                    
                    <?php if ($data->items) : ?>
                    <table id="datatable-buttons" class="table table-striped table-bordered" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                            <?php foreach (current($data->items)->fields as $field) : ?>
                                <th><?= (current($data->items)->get_alias($field))?></th>
                            <?php endforeach?>
                                
                            </tr>
                        </thead>
                            <tbody>
                            <?php foreach ($data->items as $item) : ?>
                                <tr>
                                    <?php foreach ($item->fields as $field) : ?>
                                    <td><?= h($item->$field)?></td>
                                    <?php endforeach?>
                                    
                                </tr>
                            <?php endforeach?>
                            </tbody>
                    </table>
                    <?php View::partial('paginators/digg', false, array('page' => $data ,'url' => Router::get('controller_path').'/index')) ?>

                    <?php else : // Si no hay items?>
                    <h2>No hay ningún registro</h2>
                    <?php endif ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
