
            <!-- ============================================================== -->
            <!-- Start right Content here  los archivos quedan guardados en public/javascript/assets/plugins/jquery.filer/uploads--> 
            <!-- ============================================================== -->
            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container">

                        <div class="row">
                            <div class="col-xs-12">
                                <div class="page-title-box">
                                    <h4 class="page-title">Validador</h4>
                                    <ol class="breadcrumb p-0">
                                        <li>
                                            <a href="#">Validador</a>
                                        </li>
                                        <li class="active">
                                            Uploads
                                        </li>
                                    </ol>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                        <!-- end row -->


                        <div class="row">
                            <div class="col-xs-12">
                                <div class="card-box">

                                    <div class="row">
                                        <div class="col-sm-12 col-xs-12">
                                            <h4 class="header-title m-t-0">Cargar Archivo</h4>
                                            <p class="text-muted font-13 m-b-30">
                                            Los archivos cargados quedan guardados en el server.
                                            </p>

                                            <div class="p-20">
                                                <div class="form-group clearfix">
                                                    <div class="col-sm-12 padding-left-0 padding-right-0">
                                                            <input type="file" name="files[]" id="filer_input1"
                                                               multiple="multiple">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                  <!-- End row -->

                                </div>
                            </div><!-- end col-->

                        </div>
                        <!-- end row -->


                    </div> <!-- container -->

                </div> <!-- content -->

            </div>
            <!-- End content-page -->
