            <script src="https://code.jquery.com/jquery.js"></script>
                <!-- Importo el archivo Javascript de Highcharts directamente desde su servidor -->
            <script src="http://code.highcharts.com/highcharts.js"></script>
            <script src="http://code.highcharts.com/modules/exporting.js"></script>


            <!-- ============================================================== -->
            <!-- Start right Content here  los archivos quedan guardados en public/javascript/assets/plugins/jquery.filer/uploads--> 
            <!-- ============================================================== -->
            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container">

                        <div class="row">
                            <div class="col-xs-12">
                                <div class="page-title-box">
                                    <h4 class="page-title">Estadistica</h4>
                                    <ol class="breadcrumb p-0">
                                        <li>
                                            <a href="#">ATL-FOREIA</a>
                                        </li>
                                        <li class="active">
                                            Estadistica
                                        </li>
                                    </ol>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                        <!-- end row -->
                       
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card-box table-responsive">
                                    <h4 class="m-t-0 header-title"><b>Numero de casos por Grupo de Edad</b></h4>
                                    <p class="text-muted font-13 m-b-30">
                                        Muestra el numero total de casos registrado por rango de edad de los pacientes afectados
                                    </p>
                                    <div id="contenedor" style="min-width: 310px; max-width: 800px; height: 400px; margin: 0 auto"></div>    
                                        <script type="text/javascript">

                                        Highcharts.chart('contenedor', {
                                            chart: {
                                                type: 'bar'
                                            },
                                            title: {
                                                text: 'Numero de Casos por edad'
                                            },
                                            subtitle: {
                                                text: 'Fuente: Reportes Foreia'
                                            },
                                            xAxis: {
                                                categories: [<?php echo $strcategoria ?>],
                                                title: {
                                                    text: null
                                                }
                                            },
                                            yAxis: {
                                                min: 0,
                                                title: {
                                                    text: 'Numero de casos',
                                                    align: 'high'
                                                },
                                                labels: {
                                                    overflow: 'justify'
                                                }
                                            },
                                            tooltip: {
                                                valueSuffix: ' millions'
                                            },
                                            plotOptions: {
                                                bar: {
                                                    dataLabels: {
                                                        enabled: true
                                                    }
                                                }
                                            },
                                            legend: {
                                                layout: 'vertical',
                                                align: 'right',
                                                verticalAlign: 'top',
                                                x: -40,
                                                y: 80,
                                                floating: true,
                                                borderWidth: 1,
                                                backgroundColor: ((Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'),
                                                shadow: true
                                            },
                                            credits: {
                                                enabled: false
                                            },
                                            series: [{
                                                name: 'Edad',
                                                data: [ 
                                                    
                                                    <?php echo $strdatos ?>
                                                ]
                                            }, ]
                                        });
                                        </script>
                                    
                                   
                                </div>
                            </div>
                        </div>   
                         <div class="row">
                            <div class="col-sm-12">
                                
                            </div>
                            
                        </div>

                    </div> <!-- container -->

                </div> <!-- content -->

            </div><!-- End content-page -->
