
            <!-- ============================================================== -->
            <!-- Start right Content here  los archivos quedan guardados en public/javascript/assets/plugins/jquery.filer/uploads--> 
            <!-- ============================================================== -->
            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container">

                        <div class="row">
                            <div class="col-xs-12">
                                <div class="page-title-box">
                                    <h4 class="page-title">Paciente</h4>
                                    <ol class="breadcrumb p-0">
                                        <li>
                                            <a href="#">ATL-FOREIA</a>
                                        </li>
                                        <li class="active">
                                            Paciente
                                        </li>
                                    </ol>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                        <!-- end row -->


                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card-box">

                                    <h4 class="header-title m-t-0 m-b-30">Datos Basicos</h4>

                                    <div class="row">
                                        <div class="col-lg-12 col-sm-12 col-xs-12 col-md-12 col-xl-6">
                                            <?php echo Form::open('paciente/create'); ?>
<!--                                            <form method="post">-->
                                                <fieldset class="form-group">
                                                    <label >Paciente</label>
                                                     <?php echo Form::text('paciente.identificacion', 'class="form-control" ') ?>
                                                    <small class="text-muted">Digite la Identificacion del Paciente
                                                    </small>
                                                </fieldset>
                                                <div class="row">
                                                    <div class="col-xs-4">
                                                        <fieldset class="form-group">
                                                            <label for="exampleSelect1">Sexo</label>
                                                            <?php
                                                            $sexo=array('Masculino','Femenino');
                                                            echo Form::select('paciente.sexo',$sexo,'class="form-control"') ?>
                                                        </fieldset>
                                                    </div>
                                                    <div class="col-xs-4">
                                                        <fieldset class="form-group">
                                                            <label >Edad</label>
                                                             <?php echo Form::text('paciente.edad', 'class="form-control" ') ?>

                                                        </fieldset>  
                                                    </div>
                                                    <div class="col-xs-4">
                                                        <fieldset class="form-group">
                                                            <label for="exampleSelect1">Edad en</label>
                                                            <?php
                                                            $sexo=array('dias','meses','anos');
                                                            echo Form::select('paciente.edaden',$sexo,'class="form-control"') ?>
                                                        </fieldset>
                                                    </div> 

                                                </div>
                                                
                                        </div>     
                                        <div class="col-lg-12 col-sm-12 col-xs-12 col-md-12 col-xl-6">
                                                
                                                <fieldset class="form-group">
                                                    <label >Diagnostico</label>
                                                     <?php echo Form::text('paciente.diagnostico', 'class="form-control" ') ?>
                                                    <small class="text-muted">Especifique brevemente el diagnostico del paciente al ingreso
                                                    </small>
                                                </fieldset>
                                                <?php echo Form::submit('Continuar','type="submit" class="btn btn-primary"') ?>
<!--                                                <button type="submit" class="btn btn-primary">Submit</button>-->
                                            </form>
                                        </div><!-- end col -->

                                        

                                    </div><!-- end row -->
                                </div>
                            </div><!-- end col -->
                        </div>
                        <!-- end row -->


                    </div> <!-- container -->

                </div> <!-- content -->

            </div>
            <!-- End content-page -->
