<!DOCTYPE html>
<html lang="es">
    <head>
   <!-- App Favicon -->
        <link rel="shortcut icon" href="assets/images/favicon.ico">

        <!-- App title -->
        <title>ATL-FOREIA</title>       

        <!-- Jquery filer css -->
        <?php Tag::css('assets/plugins/jquery.filer/css/jquery.filer') ?>
        <?php Tag::css('assets/plugins/jquery.filer/css/themes/jquery.filer-dragdropbox-theme') ?>
        <!-- Switchery css -->
        <?php Tag::css('assets/plugins/switchery/switchery.min') ?>
        <!-- App CSS -->
        <?php Tag::css('assets/css/style') ?>
        <!-- DataTables -->
        <?php Tag::css('assets/plugins/datatables/dataTables.bootstrap4.min') ?>
        <?php Tag::css('assets/plugins/datatables/buttons.bootstrap4.min') ?>
        <!-- Responsive datatable examples -->
        <?php Tag::css('assets/plugins/datatables/responsive.bootstrap4.min') ?>

        <!-- Switchery css -->
        <?php Tag::css('assets/plugins/switchery/switchery.min') ?>

        <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->      
        <?= Html::includeCss() ?>
        <!-- Inclusion de javascript-->
        <?php echo Tag::js('assets/js/modernizr.min') ?>
        <!--<script src="assets/js/modernizr.min.js"></script>-->
    </head>

    <body class="fixed-left">

        <!-- Begin page -->
        <div id="wrapper">

            <!-- Top Bar Start -->
            <div class="topbar">

                <!-- LOGO -->
                <div class="topbar-left">
                    <a href="#" class="logo">
                        <i class="zmdi zmdi-group-work icon-c-logo"></i>
                        <span>FOREIA</span></a>
                        
                </div>


                <nav class="navbar navbar-custom">
                    <ul class="nav navbar-nav">
                        <li class="nav-item">
                            <button class="button-menu-mobile open-left waves-light waves-effect">
                                <i class="zmdi zmdi-menu"></i>
                            </button>
                        </li>
                        <li class="nav-item hidden-mobile">
                            <form role="search" class="app-search">
                                <input type="text" placeholder="Search..." class="form-control">
                                <a href=""><i class="fa fa-search"></i></a>
                            </form>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav pull-right">
                        <li class="nav-item dropdown notification-list">
                            <a class="nav-link dropdown-toggle arrow-none waves-effect waves-light nav-user" data-toggle="dropdown" href="#" role="button"
                               aria-haspopup="false" aria-expanded="false">
                                <i class="icon-people"></i>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right dropdown-arrow profile-dropdown " aria-labelledby="Preview">
                                <!-- item-->
                                <div class="dropdown-item noti-title">
                                    
                                    <h5 class="text-overflow"><small>Bienvenido <?php echo session::get('user')?></small> </h5>
                                </div>

                                <!-- item-->
                                <a href="<?=PUBLIC_PATH;?>usuario/ver/<?php echo session::get('usuario')?>" class="dropdown-item notify-item">
                                    <i class="zmdi zmdi-account-circle"></i> <span>Perfil</span>
                                </a>

                                <!-- item-->
                                <a href="<?=PUBLIC_PATH;?>login/destroy" class="dropdown-item notify-item">
                                    <i class="zmdi zmdi-power"></i> <span>Logout</span>
                                </a>

                            </div>
                        </li>

                    </ul>

                </nav>

            </div>
            <!-- Top Bar End -->


            <!-- ========== Left Sidebar Start ========== -->
            <div class="left side-menu">
                <div class="sidebar-inner slimscrollleft">

                    <!--- Sidemenu -->
                    <div id="sidebar-menu">
                        <ul>
                            <li class="text-muted menu-title">Navegación</li>
                            
                            <li class="has_sub">
                                <a href="<?=PUBLIC_PATH;?>gestion/index" class="waves-effect active"><span class="label label-pill label-primary pull-xs-right">1</span><i class="zmdi zmdi-view-dashboard"></i><span> Dashboard </span> </a>
                            </li>

                            <li class="has_sub">
                                <a href="<?=PUBLIC_PATH;?>paciente" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Nuevo evento </span></a>
                            </li>
                            
                           <li class="has_sub">
                                <a href="#" class="waves-effect"><i class="zmdi zmdi-format-list-bulleted"></i> <span> Configuracion </span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <li><a href="<?=PUBLIC_PATH;?>dpto" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Departamentos </span></a></li>
                                    <li><a href="<?=PUBLIC_PATH;?>ciudad" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Ciudad </span></a> </li>
                                    <li><a href="<?=PUBLIC_PATH;?>ips" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Ips </span></a> </li>                                   
                                    <li><a href="<?=PUBLIC_PATH;?>clasificacion" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Clasificacion </span></a> </li>
                                    <li><a href="<?=PUBLIC_PATH;?>deteccion" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Deteccion </span></a> </li>
                                    <li><a href="<?=PUBLIC_PATH;?>desenlace" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Desenlace </span></a> </li>
                                    <li><a href="<?=PUBLIC_PATH;?>naturaleza" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Naturaleza </span></a> </li>
                                    <li><a href="<?=PUBLIC_PATH;?>causa" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Causa </span></a> </li>
                                    <li><a href="<?=PUBLIC_PATH;?>nivel" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Nivel </span></a> </li>
                                    
                                </ul>
                            </li>

                            <li class="has_sub">
                                <a href="#" class="waves-effect"><i class="zmdi zmdi-chart"></i><span> Estadisticas </span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <li><a href="<?=PUBLIC_PATH;?>estadistica/propsexo" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Por Sexo </span></a></li>
                                    <li><a href="<?=PUBLIC_PATH;?>estadistica/propeadv" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Eventos  </span></a> </li>
                                    <li><a href="<?=PUBLIC_PATH;?>estadistica/servicio" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Por Servicio </span></a> </li>                                   
                                    <li><a href="<?=PUBLIC_PATH;?>estadistica/desenlace" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Por Desenlace </span></a> </li>
                                    <li><a href="<?=PUBLIC_PATH;?>estadistica/causa" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Por Causa </span></a> </li>
                                    <li><a href="<?=PUBLIC_PATH;?>estadistica/claseevt" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Por Clase de evento </span></a> </li>
                                    <li><a href="<?=PUBLIC_PATH;?>estadistica/generico" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Por Generico </span></a> </li>
                                    <li><a href="<?=PUBLIC_PATH;?>estadistica/index" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Grupo Edad </span></a> </li>
                                    
                                </ul>
                            </li>

                            <li class="has_sub">
                                <a href="#" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span> Seguridad </span></a>
                                <ul>
                                    <li><a href="<?=PUBLIC_PATH;?>usuario" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span>Usuario </span></a></li>                                    
                                </ul>
                            </li>

                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <!-- Sidebar -->
                    <div class="clearfix"></div>

                </div>

            </div>
            <!-- Left Sidebar End -->

            <!-- vista de index-->
            <?php View::content() ?>

            <footer class="footer text-right">
               
            </footer>


        </div>
        <!-- END wrapper -->


        <script>
            var resizefunc = [];
        </script>
         
        <!-- jQuery  -->
        <?php echo Tag::js('assets/js/jquery.min') ?>
        <?php echo Tag::js('assets/js/tether.min') ?><!-- Tether for Bootstrap -->
        <?php echo Tag::js('assets/js/bootstrap.min') ?>
        <?php echo Tag::js('assets/js/detect') ?>
        <?php echo Tag::js('assets/js/fastclick') ?>
        <?php echo Tag::js('assets/js/jquery.blockUI') ?>
        <?php echo Tag::js('assets/js/waves') ?>
        <?php echo Tag::js('assets/js/jquery.nicescroll') ?>
        <?php echo Tag::js('assets/js/jquery.scrollTo.min') ?>
        <?php echo Tag::js('assets/js/jquery.slimscroll') ?>
        <?php echo Tag::js('assets/plugins/switchery/switchery.min') ?>


        <!-- flot init -->
        <?php echo Tag::js('assets/pages/jquery.flot.init') ?>
      
        <!-- Page specific js -->
       <!--  <?php //Tag::js('assets/pages/jquery.dashboard') ?>--> <!-- Counter Up  -->
        <?php echo Tag::js('assets/plugins/waypoints/lib/jquery.waypoints') ?>
        <?php echo Tag::js('assets/plugins/counterup/jquery.counterup.min') ?>
        <!-- Jquery filer js -->
        <?php echo Tag::js('assets/plugins/jquery.filer/js/jquery.filer.min') ?>
        <!-- page specific js -->
        <?php echo Tag::js('assets/pages/jquery.fileuploads.init') ?>
        <!-- Required datatable js -->
        <?php echo Tag::js('assets/plugins/datatables/jquery.dataTables.min') ?>
        <?php echo Tag::js('assets/plugins/datatables/dataTables.bootstrap4.min')?>
        <!-- Buttons examples -->
        <!-- <?php //echo Tag::js('') ?> -->
        <?php echo Tag::js('assets/plugins/datatables/dataTables.buttons.min') ?>
        <?php echo Tag::js('assets/plugins/datatables/buttons.bootstrap4.min') ?>
        <?php echo Tag::js('assets/plugins/datatables/jszip.min') ?>
        <?php echo Tag::js('assets/plugins/datatables/pdfmake.min') ?>
        <?php echo Tag::js('assets/plugins/datatables/vfs_fonts') ?>
        <?php echo Tag::js('assets/plugins/datatables/vfs_fonts') ?>
        <?php echo Tag::js('assets/plugins/datatables/buttons.html5.min') ?>
        <?php echo Tag::js('assets/plugins/datatables/buttons.print.min') ?>
        <?php echo Tag::js('assets/plugins/datatables/buttons.colVis.min') ?>
        <!-- Responsive examples -->
        <?php echo Tag::js('assets/plugins/datatables/dataTables.responsive.min') ?>
        <?php echo Tag::js('assets/plugins/datatables/responsive.bootstrap4.min') ?>
        <!-- App js -->
        <?php echo Tag::js('assets/js/jquery.core') ?>
        <?php echo Tag::js('assets/js/jquery.app') ?>

        <!-- script datatables -->
        <script type="text/javascript">
            $(document).ready(function() {
                $('#datatable').DataTable();

                //Buttons examples
                var table = $('#datatable-buttons').DataTable({
                    lengthChange: false,
                    buttons: ['copy', 'excel', 'pdf', 'colvis']
                });

                table.buttons().container()
                        .appendTo('#datatable-buttons_wrapper .col-md-6:eq(0)');
            } );

        </script>


    </body>
    
</html>
