<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        
        <meta name="author" content="Coderthemes">
       <!-- App Favicon -->
            <link rel="shortcut icon" href="default/public/favicon.ico">
            <!-- App title -->
            <title>ATL-FOREIA</title>       
            <!-- App CSS -->
            <!--<link href="assets/css/style.css" rel="stylesheet" type="text/css" /> -->
            <?php Tag::css('assets/css/style') ?>
            <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
            <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
            <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
            <![endif]-->      
            <?= Html::includeCss() ?>
            <!-- Inclusion de javascript-->
            <?php echo Tag::js('assets/js/modernizr.min') ?>
            <!--<script src="assets/js/modernizr.min.js"></script>-->
                <!-- jQuery  -->
            <?php echo Tag::js('assets/js/jquery.min') ?>
            <?php echo Tag::js('assets/js/tether.min') ?><!-- Tether for Bootstrap -->
            <?php echo Tag::js('assets/js/bootstrap.min') ?>
            <?php echo Tag::js('assets/js/detect') ?>
            <?php echo Tag::js('assets/js/fastclick') ?>
            <?php echo Tag::js('assets/js/jquery.blockUI') ?>
            <?php echo Tag::js('assets/js/waves') ?>
            <?php echo Tag::js('assets/js/jquery.nicescroll') ?>
            <?php echo Tag::js('assets/js/jquery.scrollTo.min') ?>
            <?php echo Tag::js('assets/js/jquery.slimscroll') ?>
            <?php echo Tag::js('assets/plugins/switchery/switchery.min') ?>
            <!-- App js -->
            <?php echo Tag::js('assets/js/jquery.core') ?>
            <?php echo Tag::js('assets/js/jquery.app') ?>
            <!--Efecto-->
            <?php echo Tag::js('snipper') ?>

        </head>

<body>
        <div id="particles"></div>
        <div class="modal-dialog">

                <div class="card-box m-b-0">
                    <div class="text-xs-center m-t-20">
                        <a href="#" class="logo">
                            <i class="zmdi zmdi-group-work icon-c-logo"></i>
                            <?php echo Html::img('logoatlantico.png',null,'width="90%" height="90%"') ?>
                            <span>ATL-FOREIA</span>
                        </a>
                    </div>
                    <div class="account-bg">
                        <div class="m-t-30 m-b-20">
                                <div class="col-xs-12 text-xs-center">
                                    <h6 class="text-muted text-uppercase m-b-0 m-t-0">Ingresar</h6>
                                </div>
                                    <form class="form-horizontal m-t-20" method="post" role="form">

                                        <div class="form-group ">
                                            <div class="col-xs-12">
                                                <input class="form-control" type="text" required="" placeholder="Username" name="login[user]">
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-xs-12">
                                                <input class="form-control" type="password" required="" placeholder="Password" name="login[password]">
                                            </div>
                                        </div>

                                        <div class="form-group ">
                                            <div class="col-xs-12">
                                                <div class="checkbox checkbox-custom">
                                                    <input id="checkbox-signup" type="checkbox">
                                                    <label for="checkbox-signup">
                                                        Recordarme
                                                    </label>

                                                </div>

                                            </div>
                                        </div>

                                        <div class="form-group text-center m-t-30">
                                            <div class="col-xs-12">
                                                <button class="btn btn-success btn-block waves-effect waves-light" type="submit">Log In</button>
                                            </div>
                                        </div>

                                        <div class="form-group m-t-30 m-b-0">
                                            <div class="col-sm-12">
                                                <a href="#" class="text-muted"><i class="fa fa-lock m-r-5"></i> ¿Olvidastes la contraseña?</a>
                                            </div>
                                        </div>
                                    </form>
                        </div>
                    </div>
                </div>
           
        </div>
        

        <script>
            var resizefunc = [];
        </script>

    </body>
</html>