
            <!-- ============================================================== -->
            <!-- Start right Content here  los archivos quedan guardados en public/javascript/assets/plugins/jquery.filer/uploads--> 
            <!-- ============================================================== -->
            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container">

                        <div class="row">
                            <div class="col-xs-12">
                                <div class="page-title-box">
                                    <h4 class="page-title">Dispositivos Medicos</h4>
                                    <ol class="breadcrumb p-0">
                                        <li>
                                            <a href="#">ATL-FOREIA</a>
                                        </li>
                                        <li class="active">
                                            Dispostivo Medico
                                        </li>
                                    </ol>
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                        <!-- end row -->

                        <div class="row">
                            <div class="col-sm-12">
                                <div class="card-box table-responsive">
                                    <h4 class="m-t-0 header-title"><b>Listado de eventos gestionados</b></h4>
                                    <p class="text-muted font-13 m-b-30">
                                        DataTables has most features enabled by default, so all you need to do to use it with your own tables is to call the construction function: <code>$().DataTable();</code>.
                                    </p>
                                    <table id="datatable-buttons" class="table table-striped table-bordered" cellspacing="0" width="100%">
                                        <thead>
                                            <tr>
                                                <th>Nombre Generico</th>
                                                <th>Nombre Comercial</th>
                                                <th>Reg. Sanitario</th>
                                                <th>Lote</th>
                                                <th>Modelo</th>
                                                <th>Referencia</th>
                                                <th>Serial</th>
                                                <th>Fabricante</th>
                                                <th>Distribuidor</th>
                                                <th>Area</th>
                                                <th>Usado</th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            <?php foreach ($listEventos->items as $item): ?>
                                                <tr class="gradeC">
                                                    <td><?php echo $item->generico ?></td>
                                                    <td><?php echo $item->comercial ?></td>
                                                    <td><?php echo $item->regsanitario ?></td>
                                                    <td><?php echo $item->lote ?></td>
                                                    <td><?php echo $item->modelo ?></td>
                                                    <td><?php echo $item->referencia ?></td>
                                                    <td><?php echo $item->serial ?></td>
                                                    <td><?php echo $item->fabricante ?></td>
                                                    <td><?php echo $item->distribuidor ?></td>
                                                    <td><?php echo $item->areafunc ?></td>
                                                    <td><?php echo $item->usado ?></td>                  
                                                    <td> <?php echo Html::linkAction("modificar/$item->id/", 'Editar') ?>
                                                         <?php  echo Html::linkAction("del/$item->id/", 'Borrar') ?>      
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div> <!-- end row -->


                    </div> <!-- container -->

                </div> <!-- content -->

            </div><!-- End content-page -->
